---
name: goreleaser

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
    - 
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - 
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - 
      uses: actions/cache@v3
      with:
        path: |
            ~/.cache/go-build
            ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    -
      uses: docker/setup-qemu-action@v1
    - 
      uses: docker/setup-buildx-action@v1
    - 
      uses: docker/login-action@v1
      name: ghcr.io login
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -  
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        distribution: goreleaser-pro
        args: release --rm-dist
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}